// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: src/checker/cmd/server/grpc/.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveStagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string   `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	IsFinal  bool     `protobuf:"varint,2,opt,name=IsFinal,proto3" json:"IsFinal,omitempty"`
	Stages   []*Stage `protobuf:"bytes,3,rep,name=Stages,proto3" json:"Stages,omitempty"`
}

func (x *SaveStagesRequest) Reset() {
	*x = SaveStagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_checker_cmd_server_grpc__proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveStagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStagesRequest) ProtoMessage() {}

func (x *SaveStagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_checker_cmd_server_grpc__proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStagesRequest.ProtoReflect.Descriptor instead.
func (*SaveStagesRequest) Descriptor() ([]byte, []int) {
	return file_src_checker_cmd_server_grpc__proto_rawDescGZIP(), []int{0}
}

func (x *SaveStagesRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SaveStagesRequest) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *SaveStagesRequest) GetStages() []*Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

type Stage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32                `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Score       float32              `protobuf:"fixed32,2,opt,name=Score,proto3" json:"Score,omitempty"`
	Description string               `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Duration    *durationpb.Duration `protobuf:"bytes,4,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Success     bool                 `protobuf:"varint,5,opt,name=Success,proto3" json:"Success,omitempty"`
	Actions     []*Action            `protobuf:"bytes,6,rep,name=Actions,proto3" json:"Actions,omitempty"`
}

func (x *Stage) Reset() {
	*x = Stage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_checker_cmd_server_grpc__proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_src_checker_cmd_server_grpc__proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_src_checker_cmd_server_grpc__proto_rawDescGZIP(), []int{1}
}

func (x *Stage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Stage) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Stage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Stage) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Stage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Stage) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32                `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Parameters []string             `protobuf:"bytes,2,rep,name=Parameters,proto3" json:"Parameters,omitempty"`
	IsCritical bool                 `protobuf:"varint,3,opt,name=IsCritical,proto3" json:"IsCritical,omitempty"`
	Duration   *durationpb.Duration `protobuf:"bytes,4,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Expected   []string             `protobuf:"bytes,5,rep,name=Expected,proto3" json:"Expected,omitempty"`
	Result     []string             `protobuf:"bytes,6,rep,name=Result,proto3" json:"Result,omitempty"`
	Error      []string             `protobuf:"bytes,7,rep,name=Error,proto3" json:"Error,omitempty"`
	Command    []string             `protobuf:"bytes,8,rep,name=Command,proto3" json:"Command,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_checker_cmd_server_grpc__proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_src_checker_cmd_server_grpc__proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_src_checker_cmd_server_grpc__proto_rawDescGZIP(), []int{2}
}

func (x *Action) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Action) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Action) GetIsCritical() bool {
	if x != nil {
		return x.IsCritical
	}
	return false
}

func (x *Action) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Action) GetExpected() []string {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *Action) GetResult() []string {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Action) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Action) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_checker_cmd_server_grpc__proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_src_checker_cmd_server_grpc__proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_src_checker_cmd_server_grpc__proto_rawDescGZIP(), []int{3}
}

var File_src_checker_cmd_server_grpc__proto protoreflect.FileDescriptor

var file_src_checker_cmd_server_grpc__proto_rawDesc = []byte{
	0x0a, 0x22, 0x73, 0x72, 0x63, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x63, 0x6d,
	0x64, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x11, 0x53, 0x61,
	0x76, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x49,
	0x73, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49, 0x73,
	0x46, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x23, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x52, 0x06, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73, 0x22, 0xc8, 0x01, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x08,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x26, 0x0a,
	0x07, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xf3, 0x01, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x73, 0x43, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x49, 0x73, 0x43, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c,
	0x12, 0x35, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x78, 0x70, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x45, 0x78, 0x70, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x08, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x32, 0x45, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x53, 0x61, 0x76, 0x65, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x53,
	0x74, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_checker_cmd_server_grpc__proto_rawDescOnce sync.Once
	file_src_checker_cmd_server_grpc__proto_rawDescData = file_src_checker_cmd_server_grpc__proto_rawDesc
)

func file_src_checker_cmd_server_grpc__proto_rawDescGZIP() []byte {
	file_src_checker_cmd_server_grpc__proto_rawDescOnce.Do(func() {
		file_src_checker_cmd_server_grpc__proto_rawDescData = protoimpl.X.CompressGZIP(file_src_checker_cmd_server_grpc__proto_rawDescData)
	})
	return file_src_checker_cmd_server_grpc__proto_rawDescData
}

var file_src_checker_cmd_server_grpc__proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_src_checker_cmd_server_grpc__proto_goTypes = []interface{}{
	(*SaveStagesRequest)(nil),   // 0: grpc.SaveStagesRequest
	(*Stage)(nil),               // 1: grpc.Stage
	(*Action)(nil),              // 2: grpc.Action
	(*Empty)(nil),               // 3: grpc.Empty
	(*durationpb.Duration)(nil), // 4: google.protobuf.Duration
}
var file_src_checker_cmd_server_grpc__proto_depIdxs = []int32{
	1, // 0: grpc.SaveStagesRequest.Stages:type_name -> grpc.Stage
	4, // 1: grpc.Stage.Duration:type_name -> google.protobuf.Duration
	2, // 2: grpc.Stage.Actions:type_name -> grpc.Action
	4, // 3: grpc.Action.Duration:type_name -> google.protobuf.Duration
	0, // 4: grpc.StagesService.SaveStages:input_type -> grpc.SaveStagesRequest
	3, // 5: grpc.StagesService.SaveStages:output_type -> grpc.Empty
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_src_checker_cmd_server_grpc__proto_init() }
func file_src_checker_cmd_server_grpc__proto_init() {
	if File_src_checker_cmd_server_grpc__proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_checker_cmd_server_grpc__proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveStagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_checker_cmd_server_grpc__proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_checker_cmd_server_grpc__proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_checker_cmd_server_grpc__proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_checker_cmd_server_grpc__proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_checker_cmd_server_grpc__proto_goTypes,
		DependencyIndexes: file_src_checker_cmd_server_grpc__proto_depIdxs,
		MessageInfos:      file_src_checker_cmd_server_grpc__proto_msgTypes,
	}.Build()
	File_src_checker_cmd_server_grpc__proto = out.File
	file_src_checker_cmd_server_grpc__proto_rawDesc = nil
	file_src_checker_cmd_server_grpc__proto_goTypes = nil
	file_src_checker_cmd_server_grpc__proto_depIdxs = nil
}
