// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task.Context;

#nullable disable

namespace Task.Context.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220201194121_ModelsAddDisplayIdFields")]
    partial class ModelsAddDisplayIdFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Task.Context.Models.Cadet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("Cadets");
                });

            modelBuilder.Entity("Task.Context.Models.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("Task.Context.Models.Officer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("Task.Context.Models.Cadet", b =>
                {
                    b.HasOne("Task.Context.Models.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId");

                    b.OwnsOne("Task.Context.Models.Person", "Person", b1 =>
                        {
                            b1.Property<int>("CadetId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateOnly>("BirthDate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FirstName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("LastName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("TEXT");

                            b1.HasKey("CadetId");

                            b1.ToTable("Cadets");

                            b1.WithOwner()
                                .HasForeignKey("CadetId");
                        });

                    b.Navigation("Division");

                    b.Navigation("Person")
                        .IsRequired();
                });

            modelBuilder.Entity("Task.Context.Models.Officer", b =>
                {
                    b.HasOne("Task.Context.Models.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId");

                    b.OwnsOne("Task.Context.Models.Person", "Person", b1 =>
                        {
                            b1.Property<int>("OfficerId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateOnly>("BirthDate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FirstName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("LastName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("TEXT");

                            b1.HasKey("OfficerId");

                            b1.ToTable("Officers");

                            b1.WithOwner()
                                .HasForeignKey("OfficerId");
                        });

                    b.Navigation("Division");

                    b.Navigation("Person")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
